Enhancement/4
tagtune/tagtune pull request #10
Opened 2023-05-31 06:34 UTC by Park0720

[Enhancement: Join]

[Fix: duplicate loginForm]

[Fix: 404 error after login]

[Enhancement: My information]

[Enhancement: Fit TagTune]

[Enhancement: personalForm Basic]

[Enhancement: personalForm]

[Enhancement: No information, invisible age, gender]

2023-05-31 09:40 UTC, uoise requested changes

2023-05-31 09:40 UTC, uoise commented on src/main/java/com/ll/tagtune/boundedContext/member/service/MemberService.java
> +        if (!member.equals(rq.getMember())) {
equals를 오버라이드 안해서 사용하면 안될것 같습니다.
id로 equal 비교 하시면 좋을것같습니다

2023-05-31 12:39 UTC, Park0720 commented on src/main/java/com/ll/tagtune/boundedContext/member/service/MemberService.java
> +        if (!member.equals(rq.getMember())) {
```!member.getId().equals(rq.getMember().getId())``` 이렇게 변경하면 될까요?

2023-05-31 12:46 UTC, uoise commented on src/main/java/com/ll/tagtune/boundedContext/member/service/MemberService.java
> +        if (!member.equals(rq.getMember())) {
long 이니까 ==로 충분해보입니다

2023-05-31 16:01 UTC, Park0720 commented on src/main/java/com/ll/tagtune/boundedContext/member/service/MemberService.java
> +        if (!member.equals(rq.getMember())) {
==로 수정하면 인텔리제이에서 .equals로 바꾸는 걸 추천하는데 인텔리제이에서 바꿔주는 대로 따라갈까요?

2023-06-01 00:34 UTC, uoise commented on src/main/java/com/ll/tagtune/boundedContext/member/service/MemberService.java
> +        if (!member.equals(rq.getMember())) {
넵

2023-06-01 00:35 UTC, uoise approved these changes

2023-06-01 07:08 UTC, wnstn7671 approved these changes

2023-06-01 07:25 UTC, merged