Enhancement/31
tagtune/tagtune pull request #33
Opened 2023-06-07 04:30 UTC by wnstn7671

2023-06-07 04:41 UTC, uoise requested changes

2023-06-07 04:41 UTC, uoise commented on src/main/java/com/ll/tagtune/boundedContext/member/entity/Member.java
> +import jakarta.persistence.ManyToOne;
불필요한 import 들어갔습니다

2023-06-07 04:41 UTC, uoise commented on src/main/java/com/ll/tagtune/boundedContext/playlist/controller/PlaylistController.java
> +    private final PlaylistRepository playlistRepository;
controller에서 repository 호출하면 안됩니다

2023-06-07 04:41 UTC, uoise commented on src/main/java/com/ll/tagtune/boundedContext/playlist/controller/PlaylistController.java
> +    public String deletePlaylistForm(@PathVariable Long playlistId){
메소드 이름이 deletePlaylist 여야 합니다.
폼 자체를 return 해야 할때 ~~~Form을 사용하시면 됩니다

2023-06-07 04:41 UTC, uoise commented on src/main/java/com/ll/tagtune/boundedContext/playlist/controller/PlaylistController.java
> +    public String makePlaylistForm(@Valid PlaylistForm playlistForm) {
makePlaylist 면 됩니다

2023-06-07 04:41 UTC, uoise commented on src/main/java/com/ll/tagtune/boundedContext/playlist/controller/PlaylistController.java
> +        List<Playlist> playlistByMemberId = playlistService.findAllByMemberId(rq.getMember().getId());
변수명이 playlists 면 더 이해하기 쉬울 것 같아요

2023-06-07 04:41 UTC, uoise commented on src/main/java/com/ll/tagtune/boundedContext/playlist/service/PlaylistService.java
> +    private RsData<Playlist> isValid(final Long id, final Long memberId){
isValid 로 검증을 하고 Playlist 를 가져오는 데 적절한 이름이 있을까요??

2023-06-07 04:47 UTC, Park0720 commented on src/main/java/com/ll/tagtune/boundedContext/playlist/service/PlaylistService.java
> +    private RsData<Playlist> isValid(final Long id, final Long memberId){
isMyPlaylist 이런 건 어떨까요? ㅎㅎ..

2023-06-07 05:21 UTC, parkkhee commented on src/main/java/com/ll/tagtune/boundedContext/playlist/service/PlaylistService.java
> +        if (!playlistOptional.get().getMember().getId().equals(memberId)) return RsData.of("F-2", "수정할 권한이 없습니다.");
```java
private RsData<Playlist> isValid(final Long id, final Long memberId) {
    return playlistRepository.findById(id)
            .filter(playlist -> playlist.getMember().getId().equals(memberId))
            .map(RsData::successOf)
            .orElseGet(() -> RsData.of("F-1", "해당하는 플레이리스트가 없거나 수정할 권한이 없습니다."));
}
```
이런 느낌으로도 코드 구현 가능할 것 같습니다!

2023-06-07 07:05 UTC, uoise commented on src/main/java/com/ll/tagtune/boundedContext/playlist/service/PlaylistService.java
> +        if (!playlistOptional.get().getMember().getId().equals(memberId)) return RsData.of("F-2", "수정할 권한이 없습니다.");
"잘못된 접근입니다" 로 적어도 좋을 것 같아요

2023-06-09 06:26 UTC, Park0720 approved these changes

2023-06-10 12:37 UTC, uoise approved these changes

2023-06-10 12:37 UTC, merged