Enhancement/29
tagtune/tagtune pull request #34
Opened 2023-06-07 05:00 UTC by parkkhee

Close #29

2023-06-07 05:22 UTC, Park0720 requested changes

2023-06-07 05:22 UTC, Park0720 commented on src/main/java/com/ll/tagtune/boundedContext/comment/entity/Comment.java
> +    Member member;
private 빠진 것 같습니다!

2023-06-07 05:29 UTC, Park0720 commented on src/main/java/com/ll/tagtune/boundedContext/comment/service/CommentService.java
> +@RequiredArgsConstructor
@Transactional 추가하는 게 좋지않을까요 ?

2023-06-07 06:32 UTC, uoise requested changes

2023-06-07 06:32 UTC, uoise commented on src/main/java/com/ll/tagtune/boundedContext/comment/dto/CommentResponseDTO.java
> +    public CommentResponseDTO(Long id, String content, Member writer) {
builder를 써도 될것같아요

2023-06-07 06:32 UTC, uoise commented on src/main/java/com/ll/tagtune/boundedContext/comment/dto/CommentResponseDTO.java
> +    private List<CommentResponseDTO> children = new ArrayList<>();
@Builder.Default 안걸면 null로 들어갑니다

2023-06-07 06:32 UTC, uoise commented on src/main/java/com/ll/tagtune/boundedContext/comment/entity/Comment.java
> +    @ManyToOne(fetch = FetchType.LAZY)
Lazy 건 이유를 알고싶습니다

2023-06-07 06:32 UTC, uoise commented on src/main/java/com/ll/tagtune/boundedContext/comment/entity/Comment.java
> +    public void changeDeleteStatus(Boolean deleteStatus) {
deleteStatus를 false를 기본으로 두고 isDelete로 확인해도 될 것 같아요

2023-06-07 06:32 UTC, uoise commented on src/test/java/com/ll/tagtune/boundedContext/comment/service/CommentServiceTest.java
count equal 0 보다 isEmpty, isNotEmpty를 사용하면 좋을것 같아요

2023-06-07 06:32 UTC, uoise commented on src/main/java/com/ll/tagtune/boundedContext/comment/service/CommentService.java
@Builder.Default 사용하면 빌더의 모든 기본값들을 신경쓰지 않고 작성할수 있을것 같아요
` .deleteStatus(false)`
`.children(new ArrayList<>())`
를 전부 지워도 될 것 같아요

2023-06-08 09:39 UTC, uoise requested changes

2023-06-08 09:39 UTC, uoise commented on src/main/java/com/ll/tagtune/base/event/EventAfterDelete.java
> +public class EventAfterDelete extends ApplicationEvent {
이벤트 명이 더 구체적이면 좋겠습니다

2023-06-08 09:39 UTC, uoise commented on src/main/java/com/ll/tagtune/boundedContext/comment/repository/CommentCustomRepository.java
> +public interface CommentCustomRepository {
CommentCustomRepository 대신  CommenRepositorytCustom 으로 바꿀수 있을까요

2023-06-08 09:39 UTC, uoise commented on src/test/java/com/ll/tagtune/boundedContext/comment/service/CommentServiceTest.java
> +
이부분 service에서 impl 연결하셔서 제대로 매핑 되는지 확인해야합니다

2023-06-09 06:26 UTC, Park0720 approved these changes

2023-06-12 06:19 UTC, wnstn7671 approved these changes

2023-06-13 06:35 UTC, closed without merging