Enhancement/32
tagtune/tagtune pull request #37
Opened 2023-06-08 08:26 UTC by Park0720

Filtering Tag at TagBoardPage

Apply Thymeleaf

2023-06-08 08:55 UTC, parkkhee commented
전체적으로 주석도 조금 달아주시면 좋을거 같아요:)

2023-06-08 08:58 UTC, wnstn7671 approved these changes

2023-06-08 09:36 UTC, uoise requested changes

2023-06-08 09:36 UTC, uoise commented on src/main/java/com/ll/tagtune/base/initData/NotProd.java
TagName에 중간 공백이 없으면 합니다

2023-06-08 09:36 UTC, uoise commented on src/main/java/com/ll/tagtune/boundedContext/tagBoard/controller/TagBoardController.java
> +        List<TagBoard> tagBoardList = tagBoardService.findAll();
List들을 if else 안에 넣으면 검색 시에도 모든 TagBoard 를 조회하지 않아도 될것같아요

2023-06-08 09:36 UTC, uoise commented on src/main/java/com/ll/tagtune/boundedContext/tagBoard/service/TagBoardService.java
> -    @Transactional(readOnly = true)
readOnly 들이 누락됐습니다

2023-06-08 09:36 UTC, uoise commented on src/main/resources/templates/usr/category/tagBoard.html
url이 /usr/tagboard 로 되는게 의도하신 부분일까요?

2023-06-08 09:36 UTC, uoise commented on src/main/java/com/ll/tagtune/boundedContext/tagBoard/controller/TagBoardController.java
>  @RequestMapping("usr/category")
이부분도 usr 를 의도하신 걸까요

2023-06-08 09:39 UTC, parkkhee commented on src/main/resources/templates/usr/category/tag.html
>          <h1 class="mb-4">
여기 class 에 text-[6px] 이런식으로 추가해주시면 크기 조절 가능합니다
혹시나 하고 말씀드려요!

2023-06-08 09:39 UTC, parkkhee commented on src/main/java/com/ll/tagtune/boundedContext/tagBoard/controller/TagBoardController.java
> +        List<TagBoard> top3TagBoardList = tagBoardService.findTop3ByPopularity(0L);
이건 어떤 기능인가요?.?

2023-06-08 10:38 UTC, Park0720 commented on src/main/java/com/ll/tagtune/base/initData/NotProd.java
넵 바꿔놓겠습니다~

2023-06-08 10:39 UTC, Park0720 commented on src/main/java/com/ll/tagtune/boundedContext/tagBoard/controller/TagBoardController.java
>  @RequestMapping("usr/category")
usr부분은 템플릿 usr폴더 안에 다 넣어두려고 했습니다!

2023-06-08 10:39 UTC, Park0720 commented on src/main/java/com/ll/tagtune/boundedContext/tagBoard/controller/TagBoardController.java
> +        List<TagBoard> tagBoardList = tagBoardService.findAll();
수정하겠습니다!

2023-06-08 10:41 UTC, Park0720 commented on src/main/java/com/ll/tagtune/boundedContext/tagBoard/service/TagBoardService.java
> -    @Transactional(readOnly = true)
추가했습니다!

2023-06-08 10:45 UTC, Park0720 commented on src/main/resources/templates/usr/category/tag.html
>          <h1 class="mb-4">
감사합니다! 바로 적용했습니당

2023-06-08 10:46 UTC, Park0720 commented on src/main/resources/templates/usr/category/tagBoard.html
넵 /usr/category/tagBoard로 설정해놨습니다

2023-06-08 10:47 UTC, Park0720 commented on src/main/java/com/ll/tagtune/boundedContext/tagBoard/controller/TagBoardController.java
> +        List<TagBoard> top3TagBoardList = tagBoardService.findTop3ByPopularity(0L);
findTop3 이 부분은 인기도 높은 순으로 3개만 뽑아내려고 만들어놓았습니다!

2023-06-09 06:10 UTC, uoise approved these changes

2023-06-09 06:13 UTC, merged